# Geographical and taxonomic scope -------------------

# Taxonomic granularity per survey site. All_species implies one aggregate
# number / row per site, otherwise there are multiple rows per site
taxonomic_resolution: All_species  # [All_species, Kingdom, Phylum, Class, Order, Family]
abundance_data:
  All_species: "../../../data/output/abundance/abundance_all_species.parquet"
  Kingdom: "../../../data/output/abundance/abundance_kingdom.parquet"
  Phylum: "../../../data/output/abundance/abundance_phylum.parquet"
  Class: "../../../data/output/abundance/abundance_class.parquet"
  Order: "../../../data/output/abundance/abundance_order.parquet"
  Family: "../../../data/output/abundance/abundance_family.parquet"

# TODO: Remove if not needed
group_vars:
  - SS
  - SSB
  - SSBS
  - Biome
  - Realm
  - Ecoregion
  - Biome_Realm
  - Biome_Realm_Ecoregion

# These columns are added as grouping variables, depending on taxonomic scope
# (need to include the levels above the chosen one)
taxonomic_vars:
  All_species: []
  Kingdom: [Kingdom]
  Phylum: [Kingdom, Phylum]
  Class: [Kingdom, Phylum, Class]
  Order: [Kingdom, Phylum, Class, Order]
  Family: [Kingdom, Phylum, Class, Order, Family]

# Biomes, regions and taxa need to be listed explicitly, matching the scope
# TODO: Make species part more automated if more granular scopes are to be used
scope:
  geographic:
    Biome:
      - Tropical & Subtropical Moist Broadleaf Forests
      - Tropical & Subtropical Dry Broadleaf Forests
      - Tropical & Subtropical Coniferous Forests
    UN_region: [Americas, Asia, Europe, Oceania, Africa]  # Americas, Asia, Europe, Oceania, Africa
  species:
    All_species: []  # No need to specify groups for all species
    Kingdom:
      - Animalia
      - Plantae
      - Fungi
    Phylum: []
    Class: []
    Order: []
    Family: []

# Model specification and sampler settings -------------------

# Chosen model configuration from the options listed below
model_settings:
  selected_model: model_2  # [bii_ref_model, model_1, model_2, model_3]
  model_spec: biome_realm_eco_slope  # Model object in hierarchical_models.py
  group_size_threshold: 10  # Minimum observations per group (e.g. ecoregion)

# Refer to PyMC documentation for all settings:
# https://www.pymc.io/projects/docs/en/stable/api/generated/pymc.sample.html
sampler_settings:
  draws: 500
  tune: 1000
  cores: 4
  chains: 4
  target_accept: 0.99
  nuts_sampler: "numpyro"  # [numpyro, pymc], numpyro is faster

cross_validation:
  k: 5  # Number of folds
  stratify: True  # Use stratified sampling for k-folds
  stratify_groups: [Biome_Realm_Ecoregion]  # Variable to stratify on

# Model config that matches LMM implementation in DePalma et al 2021
bii_ref_model:
  response_var: Max_scaled_abundance
  categorical_vars:
    - Primary vegetation_Light use
    - Primary vegetation_Intense use
    - Secondary vegetation_Minimal use
    - Secondary vegetation_Light use
    - Secondary vegetation_Intense use
    - Cropland_Minimal use
    - Cropland_Light_Intense
    - Pasture_Minimal use
    - Pasture_Light_Intense
    - Urban_All uses
  continuous_vars:
    - Pop_density_1km_log
    - Road_density_50km_cbrt
    - Mean_pop_density_1km_log
  interaction_cols:
    - Pop_density_1km_log
    - Road_density_50km_cbrt
  response_var_transform: null  # [adjust, sqrt, logit, null]

# Bioclimatic and topographic variables added to the reference model
model_1:
  response_var: Max_scaled_abundance
  filter_small_groups: True
  categorical_vars:
    - Primary vegetation_Light use
    - Primary vegetation_Intense use
    - Secondary vegetation_Minimal use
    - Secondary vegetation_Light use
    - Secondary vegetation_Intense use
    - Cropland_Minimal use
    - Cropland_Light_Intense
    - Pasture_Minimal use
    - Pasture_Light_Intense
    - Urban_All uses
  continuous_vars:
    - Pop_density_1km_log
    - Pop_density_50km_log
    - Road_density_1km_cbrt
    - Road_density_50km_cbrt
    - Annual_mean_temp_1km
    - Temp_seasonality_1km
    - Annual_precip_1km
    - Precip_seasonality_1km
    - Elevation_10km
    - Terrain_roughness_1km
  interaction_cols:
    - Pop_density_50km_log
    - Road_density_50km_cbrt
  response_var_transform: sqrt  # [adjust, sqrt, logit, null]

# More granular land-use categories (no grouping of light and intense use)
model_2:
  response_var: Max_scaled_abundance
  filter_small_groups: True
  categorical_vars:
    - Primary vegetation_Light use
    - Primary vegetation_Intense use
    - Secondary vegetation_Minimal use
    - Secondary vegetation_Light use
    - Secondary vegetation_Intense use
    - Cropland_Minimal use
    - Cropland_Light use
    - Cropland_Intense use
    - Pasture_Minimal use
    - Pasture_Light use
    - Pasture_Intense use
    - Urban_All uses
  continuous_vars:
    - Pop_density_1km_log
    - Pop_density_50km_log
    - Road_density_1km_cbrt
    - Road_density_50km_cbrt
    - Annual_mean_temp_1km
    - Temp_seasonality_1km
    - Annual_precip_1km
    - Precip_seasonality_1km
    - Elevation_10km
    - Terrain_roughness_1km
  interaction_cols:
    - Pop_density_50km_log
    - Road_density_50km_cbrt
  response_var_transform: sqrt  # [adjust, sqrt, logit, null]

# Simplified land-use variables (no distinction between intensities)
model_3:
  response_var: Max_scaled_abundance
  filter_small_groups: True
  categorical_vars:
    - Secondary vegetation_All uses
    - Cropland
    - Pasture
    - Urban_All uses
  continuous_vars:
    - Pop_density_1km_log
    - Pop_density_50km_log
    - Road_density_1km_cbrt
    - Road_density_50km_cbrt
    - Annual_mean_temp_1km
    - Temp_seasonality_1km
    - Annual_precip_1km
    - Precip_seasonality_1km
    - Elevation_10km
    - Terrain_roughness_1km
  interaction_cols:
    - Pop_density_50km_log
    - Road_density_50km_cbrt
  response_var_transform: sqrt  # [adjust, sqrt, logit, null]
